### ISSUE TITLE
broken example

### ISSUE THREAD

**Issue by djAlba** [legshooter/addel#3]
in example html code:

```
<div class="addel-container">
  <div class="addel-target">
    <button class="addel-del"></button>
  </div>
  <button class="addel-add"></button>
</div>
```

but classes of delete buttons must be "addel-del**ete**"

**Comment by kobykorman** [comment]
Hi,

There is no restriction on class names, only a default. You can specify your own class names with the [`classes` option](https://github.com/legshooter/addel#options). The only restriction is on the [HTML structure](https://github.com/legshooter/addel#html-structure--restrictions).

I think you mean the `README`, because `example.html` has something entirely different. So you're right in a sense, it's the old naming, inconsistent with the explanation that follows it. You are welcome to PR, or I will fix it myself later. Please do remember though that this is all customizable.

Thanks!

**Comment by kobykorman** [comment]
Released https://github.com/legshooter/addel/releases/tag/v1.2.0.
